### ISSUE TITLE
Enabling github pages on the main repo

### ISSUE THREAD

**Issue by parsampsh** [pashmaklang/pashmaklang.github.io#1]
Hi. we can enable github pages on pashmaklang/pashmak for making documentation available instead we copy everything here again. whats your say?

**Comment by parsampsh** [comment]
https://pashmaklang.github.io/pashmak/

**Comment by PooiaFerdowsi** [comment]
yes we can but will not be in rout route in get ( Route::get("/") )
else we can do it

**Comment by parsampsh** [comment]
not important.

**Comment by PooiaFerdowsi** [comment]
Okay I delete this repo in 1 day later
